name: API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WEBHOOK_URL: https://portainer.ismail-ajizou.com/api/stacks/webhooks/c2cf1b63-d6f9-435c-b158-18023b93f1f1

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: run gitops
      run: curl $WEBHOOK_URL